### ISSUE TITLE
libcamera_app.cpp fd.fd() change to fd.get()

### ISSUE THREAD

**Issue by Flap-Monster** [kbarni/LCCV#11]
Thank you for making this. I've spent a while trying to get NV12 format out of libcamera. Ended up trying to memcpy the two planes together but that didnt do it. 

Anyway, when I build this the FrameBuffer::Plane::SharedFD didnt want to build with .fd.fd().

My shared_fd.h has .fd() member under private, method get() is public.

Compiled and ran after changing this.

**Comment by kbarni** [comment]
Can you give me more details about the issue, please? Where did you encounter this?

The plane.fd.fd() was changed to plane.fd.get() in commit 5420a02c920ddef6917c6a11495c5e1f496874d6 (in January) in file `libcamera_app.cpp` line 438.

**Comment by Flap-Monster** [comment]
That's interesting, I can see it in the commit. I download the source as a zip, just re downloaded it and I can see its been changed there as well. Sorry, I'm not sure why it wasn't changed in the source I grabbed today.

I'll close this because when I redownloaded the source it was fine!
