### ISSUE TITLE
640x480 cropped

### ISSUE THREAD

**Issue by Qengineering** [kbarni/LCCV#12]
When taking a video you can set the video width and height.
```
    cam.options->video_width=3280;
    cam.options->video_height=2464;
```
Only in the 640 x 480 mode, the image is cropped to the centre of the screen, while all other resolutions have the same scene.

![image](https://user-images.githubusercontent.com/44409029/168030158-61d45c57-5300-4b1e-92a5-0b0523de5313.png)

It would be very convenient if 640 x 480 also covered the whole scene. Now I have to stream a larger format and resize it by OpenCV before processing further. Better to let the hardware work than precious computing power.

**Comment by Ar-Ray-code** [comment]
I think it is picamera's specification.
Please check following URL.

https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes

**Comment by Qengineering** [comment]
@Ar-Ray-code ,

OK, that's clear. Thanks!
