### ISSUE TITLE
Unable to compile after update of libcamera

### ISSUE THREAD

**Issue by JuergenSmo** [kbarni/LCCV#13]
Hello,
everything was working really well until today in the morning. I updated libcamera (with development packages). Then I tried to compile lccv, but with no success. The error I've got when I run make is:

pi@campi:~/LCCV/build $ make
[ 25%] Building CXX object CMakeFiles/liblccv.dir/src/lccv.cpp.o
In file included from /home/pi/LCCV/include/lccv.hpp:9,
                 from /home/pi/LCCV/src/lccv.cpp:1:
/home/pi/LCCV/include/libcamera_app.hpp: In constructor ‘FrameInfo::FrameInfo(libcamera::ControlList&)’:
/home/pi/LCCV/include/libcamera_app.hpp:192:43: error: cannot convert ‘const libcamera::Control<int>’ to ‘unsigned int’
  192 |   if (ctrls.contains(libcamera::controls::ExposureTime))
      |                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                           |
      |                                           const libcamera::Control<int>
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/liblccv.dir/build.make:82: CMakeFiles/liblccv.dir/src/lccv.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/liblccv.dir/all] Fehler 2
make: *** [Makefile:171: all] Fehler 2

Please could you take a look how this could probably be solved? 

Many thanks and BR.

**Comment by SalmanKhaja** [comment]
I am also getting almost same error when compiling :    

`||=== Build: Release in LVVC (compiler: GNU GCC Compiler) ===|
include/libcamera_app.hpp||In constructor ‘FrameInfo::FrameInfo(libcamera::ControlList&)’:|
include/libcamera_app.hpp|192|error: cannot convert ‘const libcamera::Control<int>’ to ‘unsigned int’|
include/libcamera_app.hpp||In constructor ‘FrameInfo::FrameInfo(libcamera::ControlList&)’:|
include/libcamera_app.hpp|192|error: cannot convert ‘const libcamera::Control<int>’ to ‘unsigned int’|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 11 second(s)) ===|
include/libcamera_app.hpp||In constructor ‘FrameInfo::FrameInfo(libcamera::ControlList&)’:|
include/libcamera_app.hpp|192|error: cannot convert ‘const libcamera::Control<int>’ to ‘unsigned int’|
||=== Build failed: 3 error(s), 0 warning(s) (0 minute(s), 11 second(s)) ===|
`

**Comment by SalmanKhaja** [comment]
Seems like this commit braked us : [](https://github.com/raspberrypi/libcamera-apps/commit/32c9ead4e9cdc12ba5e8a9b4ebbb7fdadaed726e#diff-bbfc0fe63361d1406f2047c1f1d27572fb7349070f88c4fe401bfb90be53ba7c)

**Comment by JuergenSmo** [comment]
@SalmanKhaja : I was now able to sucessfully compile it by modifying just the used functions. For me it is working now. 
I do not want to just upload my version here. I would prefer to use a pull request. Do you know how to open it at Github? I am sorry but I have quite less experience with Github.

**Comment by JuergenSmo** [comment]
@SalmanKhaja , @kbarni : I created a fork at https://github.com/JuergenSmo/LCCV. Please have a try if this also works for you. @kbarni : Please excuse that the readme is still your original. It would be great, if it is also working for you, if you could include the changes in your branch and I can delete my fork.

**Comment by kbarni** [comment]
@JuergenSmo can you issue a pull request, so I can merge it in the main branch?

**Comment by JuergenSmo** [comment]
@kbarni : I am not able to create a pull request. Github just say "Choose different branches or forks above to discuss and review changes. [Learn about pull requests](https://docs.github.com/articles/using-pull-requests)". 
There is only the main branch I can see. Probably I make a mistake, as said I have quite less experience with Github.

**Comment by kbarni** [comment]
Corrected. 
Thanks @JuergenSmo for the updated code!

**Comment by JuergenSmo** [comment]
you are welcome!
