### ISSUE TITLE
cam.captureFrame(image) allocates memory on each call, out of memory error

### ISSUE THREAD

**Issue by torstenschenk** [kbarni/LCCV#2]
Example project: takephoto.cpp

Add loop:

  for (int i=0;i<100;i++) {
        if(!cam.captureFrame(image)){
            std::cout<<"Camera error"<<std::endl;
        }
    }

Crash with out of mem error:
ERROR RPI raspberrypi.cpp:817 Failed to allocate buffers

**Comment by torstenschenk** [comment]
made a quick bugfix and call Teardown:

bool PiCamera::captureFrame(cv::Mat &frame)
{
    app->OpenCamera();
    app->ConfigureStill(still_flags);
    
    app->StartCamera();
    LibcameraApp::Msg msg = app->Wait();
    
    if (msg.type == LibcameraApp::MsgType::Quit)
        return false;
    else if (msg.type != LibcameraApp::MsgType::RequestComplete)
        return false;
    if (app->ViewfinderStream())
        std::cerr << "Viewfinder frame "<<std::endl;
    else if (app->StillStream())
    {
        std::cout << "still stream active\n";
        app->StopCamera();
        getImage(frame, std::get<CompletedRequestPtr>(msg.payload));
        **app->Teardown();**
        app->CloseCamera();
    }else {
        **app->Teardown();**
        app->CloseCamera();
    }
    
    return true;
}

**Comment by kbarni** [comment]
Thanks for the quick fix!
Changes pushed in `main` (commit 2227f4c9a5335125091c15586d2b68eb92df1e8e)
