### ISSUE TITLE
Debian 12(bookworm), gcc-12, atomic and memory_order

### ISSUE THREAD

**Issue by chrisd-mso** [kbarni/LCCV#24]
Trying to compile on a system running bookworm with the default g++ (g++ (Raspbian 12.2.0-14+rpi1) 12.2.0).  I get the error
In file included from /usr/include/c++/12/atomic:41,
                 from /home/cdd/projects/LCCV/include/lccv.hpp:5,
                 from /home/cdd/projects/LCCV/src/lccv.cpp:1:
In member function ‘std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]’,
    inlined from ‘bool std::atomic<bool>::load(std::memory_order) const’ at /usr/include/c++/12/atomic:112:26,
    inlined from ‘bool lccv::PiCamera::startVideo()’ at /home/cdd/projects/LCCV/src/lccv.cpp:102:20:
/usr/include/c++/12/bits/atomic_base.h:488:31: error: invalid memory model ‘memory_order_release’ for ‘unsigned char __atomic_load_1(const volatile void*, int)’ [-Werror=invalid-memory-model]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

From what I've read "memory_order" should be one of  std::memory_order_relaxed, std::memory_order_consume, std::memory_order_acquire and std::memory_order_seq_cst in an atomic::load.

I've changed line 102 of lccv.cpp from 
  if(running.load(std::memory_order_release)){
to 
  if(running.load(std::memory_order_consume)){
lccv  now compiles but I have no idea if std::memory_order_release is the correct value to use.

**Comment by berndporr** [comment]
Got the same issue under bookworm. All these "new" C++ memory management strategies are potentially very alegant but also pretty obscure.
