### ISSUE TITLE
Implementation of Manual Focus Control for Raspberry V3 Cameras

### ISSUE THREAD

**Issue by StevenAMC** [kbarni/LCCV#29]
Hi,

First of all, thank you for the great work you have done with this project.
I am wondering if there are any plans to implement the option for manual focus control on Raspberry V3 cameras. Currently, the autofocus functionality is excellent, but having the ability to adjust it manually would be very useful for some specific projects.
Is there any update or future plan for this feature?

Thank you in advance for your attention and any information you can provide.

**Comment by kbarni** [comment]
Unfortunately I don't have the V3 camera module, but if somebody can look into it, I'll be happy to add it to the library.
