### ISSUE TITLE
imshow size

### ISSUE THREAD

**Issue by Qengineering** [kbarni/LCCV#3]
Dear @kbarni,

Thanks for the nice wrapper! It is just what we needed. It requires less CPU load compared to GStreamer. 
If it is ok with you, I like to use your wrapper on my GitHub page as the default camera interface in my deep learning apps for the Raspberry Pi. Of course, I will give a credit link to your GitHub repo.

On little remark.
I had to remove this line ` cv::namedWindow("Image",cv::WINDOW_NORMAL);` in the takevideo.cpp. 
Otherwise, the imshow didn't resize to the given dimensions but stuck to a small initial square.

**Comment by kbarni** [comment]
I'm glad if you find this small wrapper useful; using libcamera directly is quite complicated.
Of course you can use it in your tutorials and projects.

Concerning `namedWindow`, it works differently if you have OpenCV with or without Ot. Use its parameters as you like.
