### ISSUE TITLE
libopencv_core.so.405, needed by /usr/local/lib/arm-linux-gnueabihf/liblccv.so

### ISSUE THREAD

**Issue by baqwas** [kbarni/LCCV#4]
Hello!

Apologies for raising this _user/operator error_ as an issue but I need your indulgence, please.

I am using Code::Blocks with your sample **takephoto** with resolution as the only modification. The code compiles without any errors or warnings (i.e. all _include_ files are pulled in correctly). Unfortunately, the build fails with the following message:

`||warning: libopencv_core.so.405, needed by /usr/local/lib/arm-linux-gnueabihf/liblccv.so, may conflict with libopencv_core.so.4.5|`

The linker options include declarations for library files as follows:

`/usr/lib/arm-linux-gnueabihf/libcamera.so
/usr/local/lib/arm-linux-gnueabihf/liblccv.so
/usr/local/lib/libopencv_core.so`

LCCV was built using your CMake instructions. Unfortunately, a modified CMake (excluding **takevideo** and correctly referencing the OpenCV and libcamera files) wouldn't build the example as a standalone executable because it couldn't find the OpenCV core library.

The platform is Raspberry Pi Zero under Bullseye. I can use the camera with GStreamer but as you can understand a lighter wrapper would be best for RPi0 work. I've read the Q-Engineering tutorial using your library but I guess I got myself into knots trying to adapt your CMakeLists.txt for equivalent use in Code::Blocks. The only extra statement in the CMakeLists.txt was the reference to the OpenCV library (and deleting the **takevideo** statement).

As you can imagine, I'm very naive about CMake/CCMake and Code::Blocks. I know that your repository should not be the first resort for 3rd party guidance but by adapting to your instructions for my simple exercise I should be able to get going with my use of the Raspberry Pi Camera under Bullseye (and avoid the heavy lifting from GStreamer). Getting LCCV to work under Code::Blocks will be a very big step for me. Thanks for your understanding.

Kind regards.

**P.S.**

The full error message at the Build step is:

`||warning: libopencv_core.so.405, needed by /usr/local/lib/arm-linux-gnueabihf/liblccv.so, may conflict with libopencv_core.so.4.5|`

I am not designating any version suffix for shared libraries in Code::Blocks build options.

**Comment by kbarni** [comment]
It seems that lccv and your program use different OpenCV installations. Try to change the Code::Blocks build file to use OpenCV 4.0.5 or vice versa.
