### ISSUE TITLE
Forcing raw video stream

### ISSUE THREAD

**Issue by wikstorm** [kbarni/LCCV#7]
It might be out of scope for this project but enabling raw frames would indeed be helpful for experimenting with different ways to handle pixel data. Would forcing the encoder to send YUV420 bayer frames be equivalent to this, or at the least close?

**Comment by kbarni** [comment]
Adding RAW frame support for photo mode is a good idea.

However YUV420 is not a Bayer format, it's already interpolated and subsampled in the chroma channel. RAW capture should return `CV_16UC1` type Mat.

**Comment by wikstorm** [comment]
I am working on the raw support and it's close to done, all I need to do is to show the frame to make sure it is working as intended.

You commented that there should be 16 bits per pixel, but the stride I read is 1.5 * width, doesn't this mean that there should be 12 bits per pixel?

**Comment by wikstorm** [comment]
I got it working. If you wish I can send you the code, but you probably want to alter it to be more flexible. Also, I only configured raw stream for video mode, not for image capturing.

**Comment by kbarni** [comment]
@wikstorm yes, please send me the code, I will try to integrate it in LCCV.
